### PR TITLE
remove summary from harvest source UI

### PR DESCRIPTION
**Pull request by FuhuXia**
fix for https://github.com/GSA/datagov-deploy/issues/874

### CODE REVIEW

**Comment by jbrown-xentity** [comment]
Before merging, can you explain why we are removing the summary section altogether?

**Comment by adborden** [comment]
Hmm, maybe we should circle up on this. I didn't realize we were fixing this by removing the summary altogether. I thought this was related to ckanext-datajson, not a fork.

As a fork, we want to be submitting things upstream as possible. Even if we are not ready to start contributing upstream yet (), we should be thinking about upstream when making changes to the forks. @FuhuXia have you read this proposal on our wiki? https://github.com/GSA/datagov-deploy/wiki/Managing-Forks I want to make sure we have a plan on how we're documenting this customization and what the plan is to get it upstream in the future.

**Comment by FuhuXia** [comment]
@adborden This commit is in line with our forking policy. This is to revert the customization we did in our fork. This customization datagov did earlier in the fork is not well tested,  it causes some issue that cannot be fixed easily without further customization of harvest extension, therefore the removal. @jbrown-xentity

**Comment by adborden** [comment]
Ah, I see your comment in [slack](https://gsa-tts.slack.com/archives/C2N85536E/p1585598643079300?thread_ts=1585583100.075400&cid=C2N85536E), okay that makes sense to me. This was a customization we added to our fork and now we're removing. That's reducing the amount of forked code we have, so sounds good to me :+1:

**Review by jbrown-xentity — APPROVED** [review]

**Comment by jbrown-xentity** [comment]
confirmed changes match upstream. Merging.

**Pull request merged**
